language: go

go:
    - 1.6
    - tip

install:
    - go get github.com/aws/aws-sdk-go/...
    - go get github.com/codegangsta/cli
    - go get github.com/Sirupsen/logrus
    - go get github.com/stretchr/testify/assert
    - go get golang.org/x/crypto/ssh
